server:
  port: 8001 #端口号

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lgq    # 所有对象类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件所在路径
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://47.100.226.134:3306/blog?characterEncoding=utf-8&useSSL=false    # 数据库名称
    username: lgq
    password: 1234